services:
  postgres:
    image: postgres:17-alpine
    container_name: vehicle-dealer-postgres
    environment:
      POSTGRES_DB: vehicle_dealer_db
      POSTGRES_USER: vehicle_user
      POSTGRES_PASSWORD: vehicle_password
    ports:
      - "5433:5432"
    volumes:
      - vehicle_dealer_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vehicle_user -d vehicle_dealer_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  vehicle_dealer_postgres_data:
